# Generated by Django 3.1.7 on 2021-06-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('thumb', models.ImageField(upload_to='images/')),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=120)),
                ('emp_email', models.CharField(max_length=120, unique=True)),
                ('emp_img', models.ImageField(upload_to='images/')),
                ('salary', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('emp_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.department')),
                ('ongoing_projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.projects')),
            ],
        ),
    ]
