# Generated by Django 3.1.7 on 2021-06-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_contact',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
